// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 13/03/2026 04:21:52
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["D:/www/Devs/Laravel_VueJs_API/laravel12-nuxt4-saas/frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/www/Devs/Laravel_VueJs_API/laravel12-nuxt4-saas/frontend/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/www/Devs/Laravel_VueJs_API/laravel12-nuxt4-saas/frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/www/Devs/Laravel_VueJs_API/laravel12-nuxt4-saas/frontend/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/www/Devs/Laravel_VueJs_API/laravel12-nuxt4-saas/frontend/app/plugins/**/*.{js,ts,mjs}","D:/www/Devs/Laravel_VueJs_API/laravel12-nuxt4-saas/frontend/app/composables/**/*.{js,ts,mjs}","D:/www/Devs/Laravel_VueJs_API/laravel12-nuxt4-saas/frontend/app/utils/**/*.{js,ts,mjs}","D:/www/Devs/Laravel_VueJs_API/laravel12-nuxt4-saas/frontend/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/www/Devs/Laravel_VueJs_API/laravel12-nuxt4-saas/frontend/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/www/Devs/Laravel_VueJs_API/laravel12-nuxt4-saas/frontend/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/www/Devs/Laravel_VueJs_API/laravel12-nuxt4-saas/frontend/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;